### PR TITLE
sync the code from original worldcoin repo

### LINKED ISSUE #32: sync the code from original worldcoin repo
https://github.com/worldcoin/world-id-state-bridge/tree/dcbuild3r/scroll

### PR DESCRIPTION
**Pull request by Ugo-X**
Resolves #32

### CODE REVIEW

**Comment by dragan2234** [comment]
@Ugo-X  I'm getting an error when running both `make build` and `forge test --chain 31337`:

```
failed to resolve file: "/Users/admin/Development/Ugo-X/worldcoin-scroll-bridge/src/mock/MockStateBridge.sol": No such file or directory (os error 2); check configured remappings
	--> /Users/admin/Development/Ugo-X/worldcoin-scroll-bridge/src/script/test/PropagateMockRoot.s.sol
	src/mock/MockStateBridge.sol
	
```
Seems like there's no folder `mock` but `mocks`. Can you please check?

**Comment by Ugo-X** [comment]
> @Ugo-X I'm getting an error when running both `make build` and `forge test --chain 31337`:
> 
> ```
> failed to resolve file: "/Users/admin/Development/Ugo-X/worldcoin-scroll-bridge/src/mock/MockStateBridge.sol": No such file or directory (os error 2); check configured remappings
> 	--> /Users/admin/Development/Ugo-X/worldcoin-scroll-bridge/src/script/test/PropagateMockRoot.s.sol
> 	src/mock/MockStateBridge.sol
> 	
> ```
> 
> Seems like there's no folder `mock` but `mocks`. Can you please check?

fixed

**Comment by dragan2234** [comment]
@Ugo-X I'm still getting errors when i run `make build` or `forge test --chain 31337`:

```
Encountered invalid solc version in src/ScrollStateBridge.sol: No solc version exists that matches the version requirement: ^0.8.27
Encountered invalid solc version in src/interfaces/IScrollCrossDomainOwnable.sol: No solc version exists that matches the version requirement: ^0.8.27
Encountered invalid solc version in src/interfaces/IScrollStateBridgeTransferOwnership.sol: No solc version exists that matches the version requirement: ^0.8.27
Found incompatible Solidity versions:
src/script/deploy/DeployScrollStateBridgeMainnet.s.sol ^0.8.16 imports:
    lib/forge-std/src/Script.sol >=0.6.2, <0.9.0
    src/ScrollStateBridge.sol ^0.8.27
...
```

**Review by dragan2234 — APPROVED** [review]
Thank you for the work!

**Pull request merged**
